[package]
name = "gbmu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.21"

[lib]
name = "gbmu"
path = "src/lib.rs"
